[gcp_service_account]

type = "service_account"

project_id = "ca-tracker-495611"

private_key_id = "f997cad4c211e983831b24fd3f3415969d1a560f"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNxvtCTg0j73Ot
N91/7UDWJDYdmtVXhsNxHLpIecfjujKRA3PGxh/hAzSXgfgDnSuf30H5xLBNRF4V
92uhK4iPw94XMLcECOi77eMRD9N6IeeWpXVWZe/om1O8jf6aNjAOUlFeK/wDrdFJ
DImKf6fkJe9iQ6bUrDumbnobL+QZF49mjTr2s5N4/UedYAG2RpjZAXLI+H/Rbdkv
VGSsImsEqRo/3MeGadxz2Q3kgMZ0v5ejKpGtSdwohJ38Rrf/+8bMdf2tTaiV66FI
ww2MIbL/px1rslM9mGkYZG1W2EWO6pJHaDNG7yhfNloLYVDlebQ520v4aLhZaY+e
Cg10LFi1AgMBAAECggEAHtjIgwbAxQWI7Ws9tsbZzJAWlacHeqyuwRbJnQI2cv6P
RHpEQYSjND+fA2Q+Ccqmhrt4wCiaNib8xKW3mmw0dzqpIQhSMxZjzwIo4v6gmMMa
3JQWjBpRVajtK0uM4lCjsQ3peSi2SVXl1OG+f4bF4/dE1JHoISLleTw/7THna1Q+
NKa2IdAMEwoF4L6Ul4X0wfS5JG2VKIQejbyBj93p8HEQgdh4jPZkRDldiLXsnOAM
OkwXv5+yoRLSg7c1hfZTjkcXFWxUhqdHJ/V98gT/C0l80Sifj7dXon0pQV3yGbpG
SkwbFNckoa5dtOQonJjWGeS+5+uIiHTvgOTvZqCikQKBgQDuIkwigK1+wOqvlo24
dSYwbdT0Lrdp5NG/voaK5L2L7l43GWCp0773XVTX5WgyIFSZqmVF4A1pqqhhJBRe
uuJCS1Mr81aGojrWLdsAPliRpQiWDLP3gSDPZiUJUSOMRyeY2KqFysVdCnog70Sz
m+JV3ZJx2sz2wTrv8I+f6xThZQKBgQDdNzo6ePoGio9Sjj7raRJ8UPJr+u4RuEcz
YOuTN5tWb7QusC6l+5r2AnRzwHrUPf2pxqch/8OQcdlNyagyN7QKdzrtLZs6PQXY
VHHyXA943L7TLtO1cDyzQcy+CER12c6H1LwKCAKx7CvTZhtdEUSxzHLWLTSouplY
XjEjfyZNEQKBgACvzqJm1pk/+y1IdN4sUFDhcDTIEbVXeJdh+EdcQ4Osy07DXvj+
aFWUSlNZEQTb/QJ4cFRUQhWk7VliXkCrr01bpEDDMeOvghXuCeylQWIiJLUyEi7L
i4mtlLvDJSQZbG7PaSZ7oDgVeKaxqfQOpgdzXSHA7MhlZEMe4XsnlWbVAoGAM537
XEF2NaiHIMBINi3iPle0+TUn78KL+pUW4tcKy/RsmqhJejlnQxf3jDrRbky4r7DG
tswzGbU2+0uej3kn7Xk8qrMFkWVDw+KQY/jPM2hurmAyzhdOUpV77KuJLeaQpmkh
J0YPOuzcnQsqP2EUIliOQyNxMh24QkJYPOwiR8ECgYEAg/bcVSwuplJXQXsYULzb
D0ddTxxXd6tb9bzarhHsnY8FXSzytp55a494YdxN6alGPo8FfvdgK/onM2w6EqcY
i8qfCMqGP5lsHnKDQnq2YNGu+lu8M+cxBJZF2KkREucn85Hj1pTVeJSnnLlxpEdI
oOM1rLkXv57q0CqpeIQmc8Y=
-----END PRIVATE KEY-----"""

client_email = "ca-tracker@ca-tracker-495611.iam.gserviceaccount.com"

client_id = "106344360941262275504"

auth_uri = "https://accounts.google.com/o/oauth2/auth"

token_uri = "https://oauth2.googleapis.com/token"

auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ca-tracker%40ca-tracker-495611.iam.gserviceaccount.com"

universe_domain = "googleapis.com"